require("core.options")
require("core.keymaps")
require("core.lazy")
-- vim.cmd([[colorscheme tokyonight]])
-- vim.cmd([[colorscheme night-owl]])
vim.cmd([[colorscheme catppuccin-mocha]])
-- vim.cmd([[colorscheme rose-pine]])
-- vim.cmd([[colorscheme nightfly]])
-- vim.cmd([[colorscheme moonfly]])
-- require("custom.templ-static-reload").setup()
